version: "3"

services:


  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    env_file:
      - .env.dist
    networks:
      - backend

  app:
    build: 
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./app/:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    networks:
      - backend

  nginx:
    build: ./nginx
    volumes:
      - ./app/:/app
    ports:
      - 80:80
    depends_on:
      - app
    networks:
      - backend

networks:
  backend:
    driver: 'bridge'

volumes:
  postgres_data: