# Generated by Django 4.0.1 on 2024-07-19 15:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_product_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.CharField(default=datetime.datetime(2024, 7, 19, 15, 3, 14, 231429), max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
    ]
