# Generated by Django 4.0.1 on 2024-07-19 18:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_order_options_alter_order_date_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='products',
        ),
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.CharField(default=datetime.datetime(2024, 7, 19, 18, 46, 51, 221412), max_length=50),
        ),
    ]
