# Generated by Django 4.0.1 on 2024-07-19 21:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_product_order_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.CharField(default=datetime.datetime(2024, 7, 19, 21, 5, 40, 432652), max_length=50),
        ),
    ]
