# Generated by Django 4.0.1 on 2024-07-19 23:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_order_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_updated',
            field=models.CharField(default=datetime.datetime(2024, 7, 19, 23, 28, 59, 696150), max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('INITIATED', 'Initiated'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='INITIATED', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.CharField(default=datetime.datetime(2024, 7, 19, 23, 28, 59, 696133), max_length=50),
        ),
    ]
